server:
  error:
    include-message: always
  forward-headers-strategy: native
  port: 18081
  servlet:
    context-path: /interviewprep

spring:
  application:
    name: service
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: https://accounts.google.com
          client-id: 905954546395-fpski4e65hfearmq04isar1tcdbth9ru.apps.googleusercontent.com