spring:
  datasource:
    url: jdbc:h2:file:./db/interviewprep
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
# Enable the following lines ONLY for DDL generation.
#    properties:
#      javax:
#        persistence:
#          schema-generation:
#            create-source: metadata
#            scripts:
#              action: create
#              create-target: docs/sql/ddl.sql